hw10
SlNata/2024-03-otus-spring-Slavich pull request #10
Opened 2024-06-24 15:35 UTC by SlNata

2024-06-27 19:40 UTC, VladimirMagerov requested changes

2024-06-27 19:40 UTC, VladimirMagerov commented on hw10/src/main/java/ru/otus/hw/rest/BookRestController.java
> +    @GetMapping("/api/allbooks")
Слово `all` к сущностям в URL добавлять не принято, оставьте просто имя сущности - `books`.
В целом, сразу подразумевается, что `GET /api/books` - получение всех книг, `GET /api/books/{id}` - получение по ID, и так далее.

2024-06-27 19:40 UTC, VladimirMagerov commented on hw10/src/main/java/ru/otus/hw/rest/BookRestController.java
> +    @GetMapping("/api/allcomments/{id}")
Если вы хотите возвращать комментарии по ID книги, по принятому подходу путь должен быть `/api/books/{id}/comments`, аналогично и для других потенциальных вложенных сущностей.

2024-06-27 19:40 UTC, VladimirMagerov commented on hw10/src/main/java/ru/otus/hw/rest/BookRestController.java
> +        Book book = bookService.findById(id).orElseThrow(EntityNotFoundException::new);
Получается, `book` тут и не нужна?

2024-06-27 19:40 UTC, VladimirMagerov commented on hw10/src/test/java/ru/otus/hw/rest/BookRestControllerTest.java
> +public class BookRestControllerTest {
Получение комментариев тоже бы надо покрыть тестами)

2024-06-28 09:36 UTC, SlNata commented on hw10/src/test/java/ru/otus/hw/rest/BookRestControllerTest.java
> +public class BookRestControllerTest {
Сделано.

2024-06-29 17:25 UTC, VladimirMagerov approved these changes

2024-06-30 03:56 UTC, merged